# Source:   {{theme-source}}
# Theme:    {{theme-name}}
# Author:   {{theme-author}}
# Variant:  {{theme-variant}}

# Default colors
[colors.primary]
background  = '{{background.hex}}'
foreground  = '{{foreground.hex}}'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text        = '{{ansi-0.hex}}'
cursor      = '{{cursor.hex}}'

# Selection colors
[colors.selection]
background  = '{{selection.hex}}'
text        = '{{selection-text.hex}}'

# Normal colors
[colors.normal]
black       = '{{ansi-0.hex}}'
red         = '{{ansi-1.hex}}'
green       = '{{ansi-2.hex}}'
yellow      = '{{ansi-3.hex}}'
blue        = '{{ansi-4.hex}}'
magenta     = '{{ansi-5.hex}}'
cyan        = '{{ansi-6.hex}}'
white       = '{{ansi-7.hex}}'

# Bright colors
[colors.bright]
black       = '{{ansi-8.hex}}'
red         = '{{ansi-9.hex}}'
green       = '{{ansi-10.hex}}'
yellow      = '{{ansi-11.hex}}'
blue        = '{{ansi-12.hex}}'
magenta     = '{{ansi-13.hex}}'
cyan        = '{{ansi-14.hex}}'
white       = '{{ansi-15.hex}}'
